window.AIF = window.AIF || {};
window.AIF.cards = [
  { domain: 1, q: "Nesting: AI, ML, deep learning, GenAI, agentic AI?", a: "AI contains ML; ML contains DL; GenAI creates content; agentic AI plans, uses tools, and acts." },
  { domain: 1, q: "Training vs inference?", a: "Training learns patterns from data. Inference applies a trained model to new inputs." },
  { domain: 1, q: "Supervised learning needs what data?", a: "Labeled examples (input → known answer). Used for classification and regression." },
  { domain: 1, q: "Unsupervised learning typical job?", a: "Clustering or anomaly detection on unlabeled data." },
  { domain: 1, q: "Reinforcement learning signal?", a: "Rewards and penalties from an environment; also used in RLHF." },
  { domain: 1, q: "Predict a number vs a category?", a: "Number = regression. Category = classification. Both are supervised." },
  { domain: 1, q: "Why accuracy lies on rare events?", a: "Always guessing the majority class still looks highly accurate. Use precision, recall, or F1." },
  { domain: 1, q: "Precision vs recall?", a: "Precision: of predicted positives, how many were right. Recall: of actual positives, how many you caught." },
  { domain: 1, q: "When is F1 useful?", a: "When you need a single balance of precision and recall." },
  { domain: 1, q: "Underfitting vs overfitting?", a: "Underfit: high error on train and test (too simple). Overfit: great train, poor new data (memorised)." },
  { domain: 1, q: "Real-time vs batch vs async inference?", a: "Real-time: user waiting. Batch: large offline jobs. Async: long jobs picked up later." },
  { domain: 1, q: "When is serverless inference a fit?", a: "Spiky or unknown traffic; pay per request; no servers to manage (e.g. Bedrock on-demand)." },
  { domain: 1, q: "When is AI the wrong tool?", a: "Need a guaranteed exact rule (tax, payroll), a simple query already works, no data, or full explainability an FM cannot give." },
  { domain: 1, q: "Traditional ML vs foundation model?", a: "Traditional ML: labeled tabular, explainability, stable numeric scores. FM: language/images, generation, little labeled data." },
  { domain: 1, q: "SageMaker Canvas vs SageMaker AI vs JumpStart?", a: "Canvas = no-code analyst ML. SageMaker AI = custom train/deploy. JumpStart = one-click pre-trained or OSS models." },
  { domain: 1, q: "Managed API vs self-hosted model API?", a: "Managed (Bedrock, Q, Rekognition) is the exam default. Self-hosted SageMaker endpoints = more control, more ops." },

  { domain: 2, q: "What is a token?", a: "A text chunk the model reads or writes. Pricing and context limits are in tokens, not words." },
  { domain: 2, q: "Context window?", a: "Max input plus output tokens the model can see in one request." },
  { domain: 2, q: "Embedding vs vector store?", a: "An embedding is a numeric meaning vector. Similar meaning → nearby vectors, stored for similarity search." },
  { domain: 2, q: "Prompt engineering vs context engineering?", a: "Prompt engineering crafts instructions. Context engineering is everything in the window: system text, retrieved docs, tools, memory, history." },
  { domain: 2, q: "Bedrock on-demand token pricing?", a: "Billed on input tokens plus output tokens (and sometimes cache tokens). Long RAG prompts raise input cost." },
  { domain: 2, q: "How to cut output token cost?", a: "Shorter answers, lower max tokens, tighter instructions. Security services do not cancel token bills." },
  { domain: 2, q: "Prompt caching vs Provisioned Throughput?", a: "Caching cheapens repeated prompt prefixes. Provisioned Throughput reserves capacity for steady high volume." },
  { domain: 2, q: "GenAI limits to name on the exam?", a: "Hallucinations, nondeterminism, weak interpretability, stale cutoff knowledge, IP/privacy/bias risk." },
  { domain: 2, q: "What is agentic AI?", a: "The model plans, calls tools, reads results, and continues until a goal is done (not just a single reply)." },
  { domain: 2, q: "What is MCP?", a: "Model Context Protocol — a standard way to connect agents to external tools and data." },
  { domain: 2, q: "Agent vs fixed workflow?", a: "Agent: steps unknown, many tools, open-ended. Fixed workflow: same pipeline every time (extract → store)." },
  { domain: 2, q: "Bedrock vs SageMaker for FMs?", a: "Bedrock: serverless multi-FM API, KB, Guardrails, Agents. SageMaker: you train, host, and operate custom models." },
  { domain: 2, q: "Amazon Q Business vs Amazon Quick?", a: "Both are workplace assistants over company knowledge. Q Developer / Kiro help builders write code." },
  { domain: 2, q: "Kiro vs Bedrock AgentCore?", a: "Kiro is an agentic IDE / coding assistant. AgentCore is how you secure and run custom production agents." },
  { domain: 2, q: "Strands Agents vs AWS Transform?", a: "Strands is a multi-agent framework. Transform modernises legacy code and applications." },
  { domain: 2, q: "Amazon Nova family idea?", a: "Micro = cheap/fast text. Lite/Pro = multimodal balance. Premier = hard reasoning / teacher. Canvas/Reel/Sonic = image/video/speech." },

  { domain: 3, q: "Low vs high temperature?", a: "Low (≈0–0.3) = focused/factual. High (≈0.7–1) = creative and more varied." },
  { domain: 3, q: "RAG in one sentence?", a: "Retrieve relevant private docs, add them to the prompt, then generate a grounded answer (ideally with citations)." },
  { domain: 3, q: "Why RAG over fine-tuning for changing facts?", a: "Cheaper, faster, citations, and you do not retrain when policies or prices change." },
  { domain: 3, q: "In-scope vector stores (not S3, not MemoryDB)?", a: "OpenSearch Service, Aurora (pgvector), RDS for PostgreSQL, Neptune. S3 holds files; MemoryDB is out of scope." },
  { domain: 3, q: "AWS default for managed RAG?", a: "Amazon Bedrock Knowledge Bases — ingest, chunk, embed, retrieve, generate." },
  { domain: 3, q: "Retrieval wrong vs generation wrong?", a: "Bad retrieved docs → chunking, hybrid search, metadata, re-rank. Good docs, bad answer → prompt, temperature, model, or grounding." },
  { domain: 3, q: "Grounding / hallucination controls?", a: "RAG + citations, Guardrails contextual grounding, schema validation, 'I don't know', A2I for high risk." },
  { domain: 3, q: "Customization ladder cheap → expensive?", a: "Prompt / few-shot → RAG → fine-tune → continued pre-training / distillation tradeoffs → almost never pre-train from scratch." },
  { domain: 3, q: "When is model distillation the play?", a: "A smaller student copies a larger teacher to cut inference cost and latency while keeping most quality." },
  { domain: 3, q: "Bedrock Prompt Management?", a: "Store, version, and roll out prompts so teams do not paste untracked prompt text in code." },
  { domain: 3, q: "Zero-shot vs few-shot vs chain-of-thought?", a: "Zero-shot = instruction only. Few-shot = examples in the prompt. CoT = think step by step for reasoning." },
  { domain: 3, q: "Jailbreak vs prompt injection vs poisoning?", a: "Jailbreak: user bypasses safety. Injection: hidden text overrides the system. Poisoning: bad data in the KB or examples." },
  { domain: 3, q: "ROUGE vs BLEU vs BERTScore?", a: "ROUGE = summary overlap. BLEU = translation overlap. BERTScore = semantic similarity, not just n-grams." },
  { domain: 3, q: "AgentCore Identity, Policy, Guardrails?", a: "Identity = who the agent is. Policy = which tools it may call. Guardrails = what content is allowed." },
  { domain: 3, q: "Chunking too big vs too small?", a: "Too big → noisy retrieval. Too small → missing context; add overlap or hierarchical chunks." },
  { domain: 3, q: "What is RLHF?", a: "Humans rank outputs, a reward model learns preferences, then the FM is reinforced toward preferred behaviour." },

  { domain: 4, q: "Name responsible AI features?", a: "Fairness, inclusivity, robustness, safety, veracity (truthfulness). Also watch bias and environmental cost." },
  { domain: 4, q: "Demographic bias vs high statistical bias?", a: "Demographic bias harms a group. High bias (underfit) is inaccurate for everyone." },
  { domain: 4, q: "Bedrock Guardrails job?", a: "Runtime filters: hate/violence/sexual, denied topics, word lists, PII, grounding, prompt-attack help." },
  { domain: 4, q: "SageMaker Clarify job?", a: "Bias detection plus feature attribution / explainability for predictions." },
  { domain: 4, q: "SageMaker Model Cards?", a: "Document intended use, metrics, limits, and data so reviewers can inspect the model." },
  { domain: 4, q: "SageMaker Model Monitor?", a: "Watch production drift and quality so you know when to retrain." },
  { domain: 4, q: "Amazon A2I when?", a: "Human review of low-confidence or high-stakes outputs before the user sees them." },
  { domain: 4, q: "Transparent vs explainable?", a: "Transparent: inspect data, design, cards, limits. Explainable: say why this specific prediction happened." },
  { domain: 4, q: "Guardrails vs a prompt 'do not…'?", a: "Prompt text is a soft request. Guardrails are a hard content control. Prefer Guardrails when you need a guarantee." },
  { domain: 4, q: "Guardrails vs IAM?", a: "Guardrails = what content is allowed. IAM = who can call which model or API." },
  { domain: 4, q: "What should training datasets be?", a: "Inclusive, diverse, curated, and balanced — not a narrow slice of one group." },
  { domain: 4, q: "AI Service Cards?", a: "AWS transparency documents for AWS AI services (intended use and limits)." },
  { domain: 4, q: "Bedrock Model Evaluation?", a: "Compare models on quality, toxicity, and task fit; can pair with LLM-as-judge." },
  { domain: 4, q: "GenAI legal / business risks?", a: "IP claims, biased outputs, lost trust, end-user harm, fluent hallucinations presented as fact." },
  { domain: 4, q: "Why FMs are often less explainable?", a: "Huge black-box weights vs a tree or linear model with feature importance. Accuracy can trade off against interpretability." },
  { domain: 4, q: "Human-centred high-stakes pattern?", a: "Show limits, collect feedback, and keep a human in the loop (A2I) for medical, legal, or credit decisions." },

  { domain: 5, q: "Shared responsibility on Bedrock?", a: "AWS secures the service and facilities. You own prompts, KB data, who may invoke, encryption choices, Guardrails, and logging." },
  { domain: 5, q: "Who may invoke a model?", a: "IAM roles, policies, least privilege, and condition keys on model IDs. Soft prompt text is not access control." },
  { domain: 5, q: "Where do secrets belong?", a: "AWS Secrets Manager (or similar) — never paste API keys into prompts." },
  { domain: 5, q: "Encryption at rest / in transit?", a: "KMS for keys at rest; TLS in transit. Customer-managed keys when the policy requires it." },
  { domain: 5, q: "PII sitting in S3 vs in model I/O?", a: "Macie discovers PII in S3. Guardrails filter PII in prompts/responses. Comprehend finds PII in text you send it." },
  { domain: 5, q: "Keep Bedrock off the public internet?", a: "AWS PrivateLink / VPC interface endpoints." },
  { domain: 5, q: "Agent identity and tool policy?", a: "Bedrock AgentCore Identity and Policy — least-privilege tools, not 'the prompt said be careful'." },
  { domain: 5, q: "Prompt injection as a Domain 5 issue?", a: "Untrusted docs or pages that say 'ignore previous' are a security problem. Use Guardrails and treat retrieved text as data." },
  { domain: 5, q: "CloudTrail vs CloudWatch vs Artifact?", a: "CloudTrail = who called which API. CloudWatch = metrics/logs/alarms. Artifact = download SOC/ISO/PCI reports." },
  { domain: 5, q: "Bedrock invocation logging?", a: "Log prompts/responses to S3 and/or CloudWatch and retain per policy. Do not put secrets in those prompts." },
  { domain: 5, q: "AWS Audit Manager vs AWS Config?", a: "Audit Manager collects ongoing compliance evidence. Config tracks resource configuration history and drift." },
  { domain: 5, q: "Data residency for GenAI?", a: "Keep data in-region; be careful with cross-region inference and where logs land." },
  { domain: 5, q: "Amazon Inspector vs Trusted Advisor?", a: "Inspector finds vulnerabilities on compute. Trusted Advisor checks account best practices and limits." },
  { domain: 5, q: "Well-Architected for AI?", a: "Use the Well-Architected Tool with ML and GenAI lenses for architecture reviews." },
  { domain: 5, q: "Does Bedrock train provider FMs on your prompts?", a: "No — a favourite exam fact. Your prompts are not used to train the base provider models by default." },
  { domain: 5, q: "Hallucination controls from a security view?", a: "RAG grounding, output validation, confidence / refuse, Guardrails grounding, and A2I — not 'just raise temperature'." }
];
